/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.crossplatform.example;

public class AndroidView extends XPView {
  private long swigCPtr;

  protected AndroidView(long cPtr, boolean cMemoryOwn) {
    super(CrossPlatformAndroidJNI.AndroidView_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AndroidView obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CrossPlatformAndroidJNI.delete_AndroidView(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AndroidView() {
    this(CrossPlatformAndroidJNI.new_AndroidView(), true);
  }

  public void updateGPSCoordinates(double latitude, double longitude) {
    CrossPlatformAndroidJNI.AndroidView_updateGPSCoordinates(swigCPtr, this, latitude, longitude);
  }

}
