/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.crossplatform.example;

public class CrossPlatformAndroidJNI {
  public final static native void XPLocation_latitude_set(long jarg1, XPLocation jarg1_, double jarg2);
  public final static native double XPLocation_latitude_get(long jarg1, XPLocation jarg1_);
  public final static native void XPLocation_longitude_set(long jarg1, XPLocation jarg1_, double jarg2);
  public final static native double XPLocation_longitude_get(long jarg1, XPLocation jarg1_);
  public final static native void XPLocation_altitude_set(long jarg1, XPLocation jarg1_, double jarg2);
  public final static native double XPLocation_altitude_get(long jarg1, XPLocation jarg1_);
  public final static native void XPLocation_speed_set(long jarg1, XPLocation jarg1_, double jarg2);
  public final static native double XPLocation_speed_get(long jarg1, XPLocation jarg1_);
  public final static native void XPLocation_heading_set(long jarg1, XPLocation jarg1_, double jarg2);
  public final static native double XPLocation_heading_get(long jarg1, XPLocation jarg1_);
  public final static native long new_XPLocation();
  public final static native void delete_XPLocation(long jarg1);
  public final static native long new_XPController();
  public final static native void delete_XPController(long jarg1);
  public final static native void XPController_setView(long jarg1, XPController jarg1_, long jarg2, XPView jarg2_);
  public final static native void XPController_getLocation(long jarg1, XPController jarg1_);
  public final static native void XPController_locationUpdated(long jarg1, XPController jarg1_, long jarg2, XPLocation jarg2_);
  public final static native long new_XPView();
  public final static native void delete_XPView(long jarg1);
  public final static native void XPView_updateGPSCoordinates(long jarg1, XPView jarg1_, double jarg2, double jarg3);
  public final static native long new_AndroidView();
  public final static native void delete_AndroidView(long jarg1);
  public final static native void AndroidView_updateGPSCoordinates(long jarg1, AndroidView jarg1_, double jarg2, double jarg3);
  public final static native long AndroidView_SWIGUpcast(long jarg1);
}
