/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.crossplatform.example;

public class XPController {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XPController(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XPController obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CrossPlatformAndroidJNI.delete_XPController(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XPController() {
    this(CrossPlatformAndroidJNI.new_XPController(), true);
  }

  public void setView(XPView view) {
    CrossPlatformAndroidJNI.XPController_setView(swigCPtr, this, XPView.getCPtr(view), view);
  }

  public void getLocation() {
    CrossPlatformAndroidJNI.XPController_getLocation(swigCPtr, this);
  }

  public void locationUpdated(XPLocation arg0) {
    CrossPlatformAndroidJNI.XPController_locationUpdated(swigCPtr, this, XPLocation.getCPtr(arg0), arg0);
  }

}
