/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.crossplatform.example;

public class XPLocation {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XPLocation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XPLocation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CrossPlatformAndroidJNI.delete_XPLocation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLatitude(double value) {
    CrossPlatformAndroidJNI.XPLocation_latitude_set(swigCPtr, this, value);
  }

  public double getLatitude() {
    return CrossPlatformAndroidJNI.XPLocation_latitude_get(swigCPtr, this);
  }

  public void setLongitude(double value) {
    CrossPlatformAndroidJNI.XPLocation_longitude_set(swigCPtr, this, value);
  }

  public double getLongitude() {
    return CrossPlatformAndroidJNI.XPLocation_longitude_get(swigCPtr, this);
  }

  public void setAltitude(double value) {
    CrossPlatformAndroidJNI.XPLocation_altitude_set(swigCPtr, this, value);
  }

  public double getAltitude() {
    return CrossPlatformAndroidJNI.XPLocation_altitude_get(swigCPtr, this);
  }

  public void setSpeed(double value) {
    CrossPlatformAndroidJNI.XPLocation_speed_set(swigCPtr, this, value);
  }

  public double getSpeed() {
    return CrossPlatformAndroidJNI.XPLocation_speed_get(swigCPtr, this);
  }

  public void setHeading(double value) {
    CrossPlatformAndroidJNI.XPLocation_heading_set(swigCPtr, this, value);
  }

  public double getHeading() {
    return CrossPlatformAndroidJNI.XPLocation_heading_get(swigCPtr, this);
  }

  public XPLocation() {
    this(CrossPlatformAndroidJNI.new_XPLocation(), true);
  }

}
