/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "XPLocation.h"
#include "XPController.h"
#include "AndroidView.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_XPLocation_1latitude_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  XPLocation *arg1 = (XPLocation *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(XPLocation **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->latitude = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_XPLocation_1latitude_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  XPLocation *arg1 = (XPLocation *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(XPLocation **)&jarg1; 
  result = (double) ((arg1)->latitude);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_XPLocation_1longitude_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  XPLocation *arg1 = (XPLocation *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(XPLocation **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->longitude = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_XPLocation_1longitude_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  XPLocation *arg1 = (XPLocation *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(XPLocation **)&jarg1; 
  result = (double) ((arg1)->longitude);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_XPLocation_1altitude_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  XPLocation *arg1 = (XPLocation *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(XPLocation **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->altitude = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_XPLocation_1altitude_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  XPLocation *arg1 = (XPLocation *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(XPLocation **)&jarg1; 
  result = (double) ((arg1)->altitude);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_XPLocation_1speed_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  XPLocation *arg1 = (XPLocation *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(XPLocation **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->speed = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_XPLocation_1speed_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  XPLocation *arg1 = (XPLocation *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(XPLocation **)&jarg1; 
  result = (double) ((arg1)->speed);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_XPLocation_1heading_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  XPLocation *arg1 = (XPLocation *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(XPLocation **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->heading = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_XPLocation_1heading_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  XPLocation *arg1 = (XPLocation *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(XPLocation **)&jarg1; 
  result = (double) ((arg1)->heading);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_new_1XPLocation(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  XPLocation *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (XPLocation *)new XPLocation();
  *(XPLocation **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_delete_1XPLocation(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  XPLocation *arg1 = (XPLocation *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(XPLocation **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_new_1XPController(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  XPController *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (XPController *)new XPController();
  *(XPController **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_delete_1XPController(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  XPController *arg1 = (XPController *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(XPController **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_XPController_1setView(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  XPController *arg1 = (XPController *) 0 ;
  XPView *arg2 = (XPView *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(XPController **)&jarg1; 
  arg2 = *(XPView **)&jarg2; 
  (arg1)->setView(arg2);
}


SWIGEXPORT void JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_XPController_1getLocation(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  XPController *arg1 = (XPController *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(XPController **)&jarg1; 
  (arg1)->getLocation();
}


SWIGEXPORT void JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_XPController_1locationUpdated(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  XPController *arg1 = (XPController *) 0 ;
  XPLocation *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(XPController **)&jarg1; 
  arg2 = *(XPLocation **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "XPLocation const & reference is null");
    return ;
  } 
  (arg1)->locationUpdated((XPLocation const &)*arg2);
}


SWIGEXPORT jlong JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_new_1XPView(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  XPView *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (XPView *)new XPView();
  *(XPView **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_delete_1XPView(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  XPView *arg1 = (XPView *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(XPView **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_XPView_1updateGPSCoordinates(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2, jdouble jarg3) {
  XPView *arg1 = (XPView *) 0 ;
  double arg2 ;
  double arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(XPView **)&jarg1; 
  arg2 = (double)jarg2; 
  arg3 = (double)jarg3; 
  (arg1)->updateGPSCoordinates(arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_new_1AndroidView(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  AndroidView *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (AndroidView *)new AndroidView();
  *(AndroidView **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_delete_1AndroidView(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  AndroidView *arg1 = (AndroidView *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(AndroidView **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_AndroidView_1updateGPSCoordinates(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2, jdouble jarg3) {
  AndroidView *arg1 = (AndroidView *) 0 ;
  double arg2 ;
  double arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AndroidView **)&jarg1; 
  arg2 = (double)jarg2; 
  arg3 = (double)jarg3; 
  (arg1)->updateGPSCoordinates(arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_com_crossplatform_example_CrossPlatformAndroidJNI_AndroidView_1SWIGUpcast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong baseptr = 0;
    (void)jenv;
    (void)jcls;
    *(XPView **)&baseptr = *(AndroidView **)&jarg1;
    return baseptr;
}

#ifdef __cplusplus
}
#endif

